---
name: xcop
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: xcop-${{ github.ref }}
  cancel-in-progress: true
jobs:
  xcop:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: g4s8/xcop-action@v1.3
        with:
          files: |
            **/*.xsl
            **/*.xml