---
name: xcop
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: xcop-${{ github.ref }}
  cancel-in-progress: true
jobs:
  xcop:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: g4s8/xcop-action@v1.3
        with:
          files: |
            **/*.xsl
            **/*.xml